import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireAdminPermission } from "@/lib/admin-guard";
import { ensureAdminSchema, logAdminActivity } from "@/lib/admin";
export const dynamic = "force-dynamic";
async function guard() {
  const auth = await requireAdminPermission("announcements");
  if (!auth.authorized) return { error: auth.response! };
  return { user: auth.user! };
}
export async function GET(){try{const g=await guard();if(g.error)return g.error;await ensureAdminSchema();const r=await db.query(`SELECT id,title,message,enabled,created_at,updated_at FROM vexo_announcements ORDER BY created_at DESC LIMIT 100`);return NextResponse.json({success:true,announcements:r.rows.map(x=>({id:x.id,title:x.title,message:x.message,enabled:x.enabled,createdAt:x.created_at,updatedAt:x.updated_at}))})}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:"Unable to load announcements."},{status:500})}}
export async function POST(req:Request){try{const g=await guard();if(g.error)return g.error;await ensureAdminSchema();const b=await req.json(),title=String(b?.title||"").trim(),message=String(b?.message||"").trim();if(title.length<2||title.length>160||message.length<2||message.length>3000)return NextResponse.json({success:false,error:"Enter a valid title and message."},{status:400});const r=await db.query(`INSERT INTO vexo_announcements(title,message,enabled,created_by) VALUES($1,$2,$3,$4) RETURNING id,title,message,enabled,created_at`,[title,message,b?.enabled!==false,+g.user!.id]);await logAdminActivity(+g.user!.id,"announcement_create","announcement",String(r.rows[0].id),{title});return NextResponse.json({success:true,announcement:r.rows[0]})}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:"Unable to create announcement."},{status:500})}}
export async function PATCH(req:Request){try{const g=await guard();if(g.error)return g.error;await ensureAdminSchema();const b=await req.json(),id=String(b?.id||"");const r=await db.query(`UPDATE vexo_announcements SET title=COALESCE(NULLIF($2,''),title),message=COALESCE(NULLIF($3,''),message),enabled=COALESCE($4,enabled),updated_at=NOW() WHERE id=$1 RETURNING id,title,message,enabled`,[id,String(b?.title||""),String(b?.message||""),typeof b?.enabled==='boolean'?b.enabled:null]);if(!r.rows[0])return NextResponse.json({success:false,error:"Announcement not found."},{status:404});await logAdminActivity(+g.user!.id,"announcement_update","announcement",id,{enabled:b?.enabled});return NextResponse.json({success:true,announcement:r.rows[0]})}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:"Unable to update announcement."},{status:500})}}
export async function DELETE(req:Request){try{const g=await guard();if(g.error)return g.error;await ensureAdminSchema();const id=new URL(req.url).searchParams.get("id")||"";const r=await db.query(`DELETE FROM vexo_announcements WHERE id=$1 RETURNING id`,[id]);if(!r.rows[0])return NextResponse.json({success:false,error:"Announcement not found."},{status:404});await logAdminActivity(+g.user!.id,"announcement_delete","announcement",id);return NextResponse.json({success:true})}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:"Unable to delete announcement."},{status:500})}}
